<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- <script src="./promise.js"></script> -->
  </head>
  <body>
    <script>
      let p = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("OK!");
          // reject("err");
        }, 1000);
        // throw "error"
      });
      let res = p.then(
        (value) => {
          return new Promise((resolve, reject) => {
            resolve("s");
          });
        },
        (reason) => {
          throw "err";
        }
      );
      console.log(res);

      // console.log(p);
      //   .then((value) => {
      //     console.log(222);
      //   })
      //   .catch((reasoe) => {
      //     //异常穿透 链式调用中如果失败的话会直接调用到这个函数
      //     console.error(reasoe);
      //   });
    </script>
  </body>
</html>
